name: "Build legacy Nix package on Ubuntu"

on:
  push:

jobs:
  legacy-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: cachix/install-nix-action@v19
      - name: Building package
        run: nix-build . -A packages.x86_64-linux.default
  flake-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: cachix/install-nix-action@v19
      - name: Building package
        run: nix build .
